[package]
name = "minigrep"
version = "0.1.0"
authors = ["Albert Islamov <higashi166@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "minigrep"
path = "src/lib.rs"

[dependencies]
